services:
  - type: web
    name: idg-dashboard
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:ke/0kRgO2IurYeKwHPXRRDhFKwHfFhtJj3+GblWdHi0=
